services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1234:1234"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_WS_URL: ws://localhost:1234
    ports:
      - "1267:1267"
    depends_on:
      - backend